version: '3'
services:
  opentariff:
    image: docker.pkg.github.com/it108/opentariff/opentariff:${GITHUB_SHA}
    container_name: opentariff
    restart: always
    environment:
      SEARCH_ENDPOINT: ${OT_APPSEARCH_ENDPOINT}:3002/api/as/v1
      SEARCH_API_KEY: ${SEARCH_API_KEY}
      SEARCH_ENGINE_NAME: ${SEARCH_ENGINE_NAME}
    ports:
    - "${OT_PORT}:80"
    networks:
      - ot

  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      node.name: es-node
      discovery.type: single-node
      cluster.name: app-search-docker-cluster
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    networks:
      ot:
       ipv4_address: ${OT_ELASTICSEARCH_ENDPOINT}

  appsearch:
    hostname: appsearch
    image: docker.elastic.co/enterprise-search/enterprise-search:7.8.0
    environment:
      elasticsearch.host: http://elasticsearch:9200
      elasticsearch.username: elastic
      elasticsearch.password: changeme
      ent_search.external_url: http://${OT_APPSEARCH_ENDPOINT}:3002
      ent_search.listen_host: ${OT_APPSEARCH_ENDPOINT}
      allow_es_settings_modification: 'true'
      secret_management.encryption_keys: '[4a2cd3f81d39bf28738c10db0ca782095ffac07279561809eecc722e0c20eb09]'
    networks:
      ot:
       ipv4_address: ${OT_APPSEARCH_ENDPOINT}


volumes:
  esdata01:
    driver: local

networks:
  ot:
    external:
      name: opentariff_network_prod
