version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      node.name: es-node
      discovery.type: single-node
      cluster.name: app-search-docker-cluster
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1

  appsearch:
    image: docker.elastic.co/enterprise-search/enterprise-search:7.8.0
    ports:
      - "3002:3002"
    environment:
      elasticsearch.host: http://elasticsearch:9200
      elasticsearch.username: elastic
      elasticsearch.password: changeme
      allow_es_settings_modification: 'true'
      secret_management.encryption_keys: '[4a2cd3f81d39bf28738c10db0ca782095ffac07279561809eecc722e0c20eb09]'
